// SQL Query để lấy dữ liệu sản xuất từ WAVEDLIB
const config = require('../config');

const productionQueries = {
    // Production Report - An toàn với parameterized queries
    productionReportComplex: `
    SELECT DISTINCT
        TRIM(A.LN1C9D)||'-'||TRIM(A.LN2C9D) as Line, TRIM(CN1I09) as Line_Name,
        CASE WHEN A.PDSC9D = '1' THEN 'REMAKE' ELSE '' END as REMAKE,
        PSHN9Y as REMAKE_LINK, A.PSHN9D as PR, A.ITMC9D as ITEM, TRIM(IT1IA0) as ITEM1,
        TRIM(IT2IA0) as ITEM2, TRIM(IT3IA0) as ITEM3, TRIM(CLSCA0) as CLASS, A.LNGV9D as Leng,
        A.LUNC9D as Unit, A.CLRC9D as Color, A.PSCQ9D as qty, A.PSDU9D as START_D,
        A.PSDT9D as START_T, A.EPFU9D as EST_COM_D, A.EPFT9D as EST_COM_T,
        A.PCPU9D as ACT_COM_D, A.PCMT9D as ACT_COM_T,
        CASE WHEN A.PCPU9D <= A.EPFU9D THEN 'ONTIME' ELSE 'DELAY' END AS DELAY_DAY,
        CASE 
            WHEN A.PCPU9D IS NULL AND TQ090.RUPUQ0 IS NOT NULL THEN 'Hoàn thành tại Sewing'
            WHEN A.PCPU9D IS NOT NULL THEN 'ONTIME COMPLETED'
            ELSE 'NOT COMPLETE' 
        END AS COM_STATUS,
        A.PCPQ9D AS COMP_PCS, MC_DATE, MC_TIME, STATUS, E.RADUV1 AS PRINT_D,
        E.RADTV1 AS PRINT_T, TQ090.RUPUQ0, TQ090.RUPTQ0
    FROM WAVEDLIB.F9D00 AS A
        LEFT JOIN WAVEDLIB.F9Y00 ON A.PSCN9D = APSN9Y
        INNER JOIN WAVEDLIB.F9F00 ON A.PSCN9D = PSCN9F
        INNER JOIN WAVEDLIB.FA000 ON A.ITMC9D = ITMCA0
        LEFT JOIN WAVEDLIB.C0900 ON WAVEDLIB.C0900.DGRC09 = 'LN1C' AND A.LN1C9D = SUBSTRING(WAVEDLIB.C0900.DDTC09,1,3) AND A.LN2C9D = SUBSTRING(WAVEDLIB.C0900.DDTC09,4,2) AND SUBSTRING(WAVEDLIB.C0900.DDTC09,6,2) ='01'
        LEFT JOIN WAVEDLIB.FC730V1 AS E ON A.PSHN9D = E.PSHNV1
        LEFT JOIN WAVEDLIB.F9G00 ON A.PSHN9D = PSHN9G
        LEFT JOIN WAVEDLIB.TRZ50 ON A.PSHN9D = TRZ50.PSHNRZ
        LEFT JOIN S7831F70.WAVEDLIB.TQ090 AS TQ090 ON TRIM(CASE WHEN TRZ50.MSACRZ = 'CUT' THEN TRZ50.WABCRZ ELSE TRZ50.BKTNRZ END) = TRIM(TQ090.BINCQ0)
        LEFT JOIN (
            SELECT ZPR, ZPPTN AS MC_TYPE, ZPPLC, ZPGSC, ZPSDU, ZSSTT, ZPCPU, ZPPMC, ZPCMT,
                CASE WHEN ZPCPU >= ZPSDU THEN ZPCPU ELSE ZPSDU END AS MC_DATE,
                CASE WHEN ZPCPU >= ZPSDU THEN ZPCMT ELSE ZSSTT END AS MC_TIME,
                CASE WHEN ZPCPU >= ZPSDU THEN (TRIM(ZPGSC)||'E') ELSE (TRIM(ZPGSC)||'S') END AS STATUS,
                (TRIM(ZPPLC) || '-' || TRIM(ZPPMC)) AS MC_LINE
            FROM (
                SELECT ROW_NUMBER() OVER(ORDER BY Z.PSHNAB) AS ZNO,
                    Z.PSHNAB AS ZPR, Z.PPTNAB AS ZPPTN, Z.PPLCAB AS ZPPLC, Z.PGSCAB AS ZPGSC,
                    Z.PSDUAB AS ZPSDU, Z.SSTTAB AS ZSSTT, Z.PCPUAB AS ZPCPU, Z.PPMCAB AS ZPPMC, Z.PCMTAB AS ZPCMT
                FROM WAVEDLIB.FAB00 AS Z
                INNER JOIN ( SELECT X.PSHN9D AS XPSHN FROM WAVEDLIB.F9D00 AS X WHERE X.PSDU9D BETWEEN ? AND ? AND SUBSTRING(X.LN1C9D,1,3) = ? ) ON Z.PSHNAB = XPSHN
            )
            INNER JOIN (
                SELECT CPR, MAX(NO) AS MAX_NO
                FROM (
                    SELECT ROW_NUMBER() OVER(ORDER BY C.PSHNAB) AS NO,
                        C.PSHNAB AS CPR, C.PPTNAB AS CPPTN, C.PPLCAB AS CPPLC, C.PGSCAB AS CPGSC
                    FROM WAVEDLIB.FAB00 AS C
                    INNER JOIN ( SELECT Y.PSHN9D AS YPSHN FROM WAVEDLIB.F9D00 AS Y WHERE Y.PSDU9D BETWEEN ? AND ? AND SUBSTRING(Y.LN1C9D,1,3) = ? ) ON C.PSHNAB = YPSHN
                )
                GROUP BY CPR
            ) ON ZNO = MAX_NO
        ) ON A.PSHN9D = ZPR
    WHERE A.PSDU9D BETWEEN ? AND ?
        AND SUBSTRING(A.LN1C9D,1,3) = ?
        AND A.PSDU9D > 0
    ORDER BY A.PSDU9D DESC, A.PSDT9D DESC
    FETCH FIRST ? ROWS ONLY`.replace(/\\n\\s+/g, ' ').trim(),

    // Query để chỉ lấy Production Report updates
    productionReportUpdates: `
    SELECT DISTINCT
        TRIM(A.LN1C9D)||'-'||TRIM(A.LN2C9D) as Line, TRIM(CN1I09) as Line_Name,
        CASE WHEN A.PDSC9D = '1' THEN 'REMAKE' ELSE '' END as REMAKE,
        PSHN9Y as REMAKE_LINK, A.PSHN9D as PR, A.ITMC9D as ITEM, TRIM(IT1IA0) as ITEM1,
        TRIM(IT2IA0) as ITEM2, TRIM(IT3IA0) as ITEM3, TRIM(CLSCA0) as CLASS, A.LNGV9D as Leng,
        A.LUNC9D as Unit, A.CLRC9D as Color, A.PSCQ9D as qty, A.PSDU9D as START_D,
        A.PSDT9D as START_T, A.EPFU9D as EST_COM_D, A.EPFT9D as EST_COM_T,
        A.PCPU9D as ACT_COM_D, A.PCMT9D as ACT_COM_T,
        CASE WHEN A.PCPU9D <= A.EPFU9D THEN 'ONTIME' ELSE 'DELAY' END AS DELAY_DAY,
        CASE 
            WHEN A.PCPU9D IS NULL AND TQ090.RUPUQ0 IS NOT NULL THEN 'Hoàn thành tại Sewing'
            WHEN A.PCPU9D IS NOT NULL THEN 'ONTIME COMPLETED'
            ELSE 'NOT COMPLETE' 
        END AS COM_STATUS,
        A.PCPQ9D AS COMP_PCS, MC_DATE, MC_TIME, STATUS, E.RADUV1 AS PRINT_D,
        E.RADTV1 AS PRINT_T, TQ090.RUPUQ0, TQ090.RUPTQ0
    FROM WAVEDLIB.F9D00 AS A
        LEFT JOIN WAVEDLIB.F9Y00 ON A.PSCN9D = APSN9Y
        INNER JOIN WAVEDLIB.F9F00 ON A.PSCN9D = PSCN9F
        INNER JOIN WAVEDLIB.FA000 ON A.ITMC9D = ITMCA0
        LEFT JOIN WAVEDLIB.C0900 ON WAVEDLIB.C0900.DGRC09 = 'LN1C' AND A.LN1C9D = SUBSTRING(WAVEDLIB.C0900.DDTC09,1,3) AND A.LN2C9D = SUBSTRING(WAVEDLIB.C0900.DDTC09,4,2) AND SUBSTRING(WAVEDLIB.C0900.DDTC09,6,2) ='01'
        LEFT JOIN WAVEDLIB.FC730V1 AS E ON A.PSHN9D = E.PSHNV1
        LEFT JOIN WAVEDLIB.F9G00 ON A.PSHN9D = PSHN9G
        LEFT JOIN WAVEDLIB.TRZ50 ON A.PSHN9D = TRZ50.PSHNRZ
        LEFT JOIN S7831F70.WAVEDLIB.TQ090 AS TQ090 ON TRIM(CASE WHEN TRZ50.MSACRZ = 'CUT' THEN TRZ50.WABCRZ ELSE TRZ50.BKTNRZ END) = TRIM(TQ090.BINCQ0)
        LEFT JOIN (
            SELECT ZPR, ZPPTN AS MC_TYPE, ZPPLC, ZPGSC, ZPSDU, ZSSTT, ZPCPU, ZPPMC, ZPCMT,
                CASE WHEN ZPCPU >= ZPSDU THEN ZPCPU ELSE ZPSDU END AS MC_DATE,
                CASE WHEN ZPCPU >= ZPSDU THEN ZPCMT ELSE ZSSTT END AS MC_TIME,
                CASE WHEN ZPCPU >= ZPSDU THEN (TRIM(ZPGSC)||'E') ELSE (TRIM(ZPGSC)||'S') END AS STATUS,
                (TRIM(ZPPLC) || '-' || TRIM(ZPPMC)) AS MC_LINE
            FROM (
                SELECT ROW_NUMBER() OVER(ORDER BY Z.PSHNAB) AS ZNO,
                    Z.PSHNAB AS ZPR, Z.PPTNAB AS ZPPTN, Z.PPLCAB AS ZPPLC, Z.PGSCAB AS ZPGSC,
                    Z.PSDUAB AS ZPSDU, Z.SSTTAB AS ZSSTT, Z.PCPUAB AS ZPCPU, Z.PPMCAB AS ZPPMC, Z.PCMTAB AS ZPCMT
                FROM WAVEDLIB.FAB00 AS Z
                INNER JOIN ( SELECT X.PSHN9D AS XPSHN FROM WAVEDLIB.F9D00 AS X WHERE SUBSTRING(X.LN1C9D,1,3) = ? ) ON Z.PSHNAB = XPSHN
            )
            INNER JOIN (
                SELECT CPR, MAX(NO) AS MAX_NO
                FROM (
                    SELECT ROW_NUMBER() OVER(ORDER BY C.PSHNAB) AS NO,
                        C.PSHNAB AS CPR, C.PPTNAB AS CPPTN, C.PPLCAB AS CPPLC, C.PGSCAB AS CPGSC
                    FROM WAVEDLIB.FAB00 AS C
                    INNER JOIN ( SELECT Y.PSHN9D AS YPSHN FROM WAVEDLIB.F9D00 AS Y WHERE SUBSTRING(Y.LN1C9D,1,3) = ? ) ON C.PSHNAB = YPSHN
                )
                GROUP BY CPR
            ) ON ZNO = MAX_NO
        ) ON A.PSHN9D = ZPR
    WHERE SUBSTRING(A.LN1C9D,1,3) = ?
        AND A.PSDU9D > 0
        AND (TQ090.RUPUQ0 > ? OR (TQ090.RUPUQ0 = ? AND TQ090.RUPTQ0 > ?))
    ORDER BY A.PSDU9D DESC, A.PSDT9D DESC`.replace(/\\n\\s+/g, ' ').trim(),

    // Query để lấy các chỉ số thống kê cho dashboard
    getMonthlyStats: `
        SELECT
            COUNT(PSHN9D) AS total_pr,
            SUM(CASE WHEN PCPU9D > 0 AND PCPU9D > EPFU9D THEN 1 ELSE 0 END) AS delayed_pr,
            SUM(PSCQ9D) AS total_planned_qty,
            SUM(PCPQ9D) AS total_actual_qty
        FROM
            WAVEDLIB.F9D00
        WHERE
            EPFU9D BETWEEN ? AND ?
            AND PSDU9D > 0
    `.replace(/\\n\\s+/g, ' ').trim(),

    // Query để lấy các sự kiện cho lịch sản xuất
    getCalendarEvents: `
        SELECT
            PSHN9D AS title,
            EPFU9D AS start_date
        FROM
            WAVEDLIB.F9D00
        WHERE
            EPFU9D BETWEEN ? AND ?
            AND PSDU9D > 0
        ORDER BY
            EPFU9D
    `.replace(/\\n\\s+/g, ' ').trim()
};

module.exports = productionQueries;