// SQL Query để lấy dữ liệu sản xuất từ WAVEDLIB
const config = require('../config');

const productionQueries = {
    // Production Report - Đầy đủ chi tiết
    productionReportComplex: `SELECT 
        A.LN1C9D||'-'|| A.LN2C9D as Line,
        CN1I09 as Line_Name,
        CASE WHEN A.PDSC9D = '1' THEN 'REMAKE' ELSE '' END as REMAKE,
        PSHN9Y as REMAKE_LINK,
        A.PSHN9D as PR,
        A.ITMC9D as ITEM,
        IT1IA0 as ITEM1,
        IT2IA0 as ITEM2,
        IT3IA0 as ITEM3,
        CLSCA0 as CLASS,
        A.LNGV9D as Leng,
        A.LUNC9D as Unit,
        A.CLRC9D as Color,
        A.PSCQ9D as qty,
        PSDU9G as START_D,
        PSDT9G as START_T,
        A.EPFU9D as EST_COM_D,
        A.EPFT9D as EST_COM_T,
        A.PCPU9D as ACT_COM_D,
        A.PCMT9D as ACT_COM_T,
        CASE WHEN A.PCPU9D <= A.EPFU9D THEN 'ONTIME' ELSE 'DELAY' END AS DELAY_DAY,
        CASE WHEN A.PCPU9D || A.PCPC9D <= A.EPFU9D || A.EPFC9D THEN 'ONTIME' ELSE 'DELAY' END AS DELAY_UNIT,
        CASE WHEN A.PCPU9D > '0' THEN 'COMPLETED' ELSE MC_TYPE || ' ' || MC_LINE || STATUS END AS AREA,
        CASE WHEN A.PCPU9D > 0 THEN 'COMPLETED' ELSE 'NOT COMPLETE' END AS COM_STATUS,
        A.PCPQ9D AS COMP_PCS,
        MC_DATE,
        MC_TIME,
        STATUS,
        E.RADUV1 AS PRINT_D,
        E.RADTV1 AS PRINT_T,
        TAPE_OUT,
        TP_AREA,
        TQ090.RUPUQ0,
        TQ090.RUPTQ0
    FROM WAVEDLIB.F9D00 AS A
        LEFT JOIN WAVEDLIB.F9Y00 ON A.PSCN9D = APSN9Y
        INNER JOIN WAVEDLIB.F9F00 ON A.PSCN9D = PSCN9F
        INNER JOIN WAVEDLIB.FA000 ON A.ITMC9D = ITMCA0
        LEFT JOIN WAVEDLIB.C0900 ON WAVEDLIB.C0900.DGRC09 = 'LN1C'
            AND A.LN1C9D = SUBSTRING(WAVEDLIB.C0900.DDTC09,1,3) 
            AND A.LN2C9D = SUBSTRING(WAVEDLIB.C0900.DDTC09,4,2) 
            AND SUBSTRING(WAVEDLIB.C0900.DDTC09,6,2) ='01'
        LEFT JOIN WAVEDLIB.FC730V1 AS E ON A.PSHN9D = E.PSHNV1
        LEFT JOIN WAVEDLIB.FC730V2 AS F ON A.PSHN9D = F.PSHNV1
        LEFT JOIN WAVEDLIB.F9G00 ON A.PSHN9D = PSHN9G
        LEFT JOIN WAVEDLIB.TRZ50 ON A.PSHN9D = TRZ50.PSHNRZ
        LEFT JOIN S7831F70.WAVEDLIB.TQ090 AS TQ090
            ON TRIM(CASE WHEN TRZ50.MSACRZ = 'CUT' THEN TRZ50.WABCRZ ELSE TRZ50.BKTNRZ END) = TRIM(TQ090.BINCQ0)
        LEFT JOIN (
            SELECT S.PSHNQ2 AS SL_PR, S.PU2CQ2 AS SL_AREA, SF.CLSCA0 AS SL_CLASS 
            FROM WAVEDLIB.TQ220 AS S 
            INNER JOIN WAVEDLIB.FA000 AS SF ON SF.ITMCA0 = S.MITCQ2 
            WHERE SF.CLSCA0 = 'PS' 
            GROUP BY S.PSHNQ2, S.PU2CQ2, SF.CLSCA0
        ) ON SL_PR = A.PSHN9D
        LEFT JOIN (
            SELECT TP.PSHNQ2 AS TP_PR, TP.PU2CQ2 AS TP_AREA, TPF.CLSCA0 AS TPF_CLASS 
            FROM WAVEDLIB.TQ220 AS TP 
            INNER JOIN WAVEDLIB.FA000 AS TPF ON TPF.ITMCA0 = TP.MITCQ2 
            WHERE TPF.CLSCA0 = 'T' OR TPF.CLSCA0 = 'CH' 
            GROUP BY TP.PSHNQ2, TP.PU2CQ2, TPF.CLSCA0
        ) ON TP_PR = A.PSHN9D
        LEFT JOIN (
            SELECT PSHNQ2 AS CHIP_PR, MAX(RADUQ2) AS CHIP_OUT 
            FROM WAVEDLIB.TQ220 
            WHERE MITCQ2 = '0006251' AND BINCQ2 <> OBINQ2 
            GROUP BY PSHNQ2
        ) ON A.PSHN9D = CHIP_PR
        LEFT JOIN (
            SELECT PSCNQ1 AS CH_PP, EPFUQ1 AS CH_D, 
                CASE WHEN SUBSTRING(LN1CQ1,1,2) = '21' THEN ROUND(PSCQQ1*CLLVQ1/100,2) ELSE PSCQQ1 END AS CH_QTY, 
                EPFTQ1 AS CH_T 
            FROM WAVEDLIB.FQ180 
            WHERE SUBSTRING(LN1CQ1,1,2) = '21' OR SUBSTRING(LN1CQ1,1,2) = '41'
        ) ON A.PSCN9D = CH_PP
        LEFT JOIN (
            SELECT G.PSHNRZ AS TAPEPR, MAX(G.RUPURZ) AS TAPE_OUT 
            FROM WAVEDLIB.TRZ50 AS G 
            WHERE CASE WHEN SUBSTRING(G.CUOCRZ,1,2) = 'KF' THEN G.MSACRZ ELSE 'CUT       ' END = G.MSACRZ 
            AND G.WABCRZ <> '' 
            GROUP BY G.PSHNRZ
        ) ON A.PSHN9D = TAPEPR
        LEFT JOIN (
            SELECT H.PSHNRZ AS PICKPR, MAX(H.RUPURZ) AS SL_OUT 
            FROM WAVEDLIB.TRZ50 AS H 
            WHERE H.MSACRZ = 'PICK      ' 
            GROUP BY H.PSHNRZ
        ) ON A.PSHN9D = PICKPR
        LEFT JOIN (
            SELECT ZPR, ZPPTN AS MC_TYPE, ZPPLC, ZPGSC, ZPSDU, ZSSTT, ZPCPU, ZPPMC, ZPCMT,
                CASE WHEN ZPCPU >= ZPSDU THEN ZPCPU ELSE ZPSDU END AS MC_DATE,
                CASE WHEN ZPCPU >= ZPSDU THEN ZPCMT ELSE ZSSTT END AS MC_TIME,
                CASE WHEN ZPCPU >= ZPSDU THEN (ZPGSC||'E') ELSE (ZPGSC||'S') END AS STATUS,
                (ZPPLC || '-' || ZPPMC) AS MC_LINE
            FROM (
                SELECT ROW_NUMBER() OVER(ORDER BY Z.PSHNAB) AS ZNO,
                    Z.PSHNAB AS ZPR, Z.PPTNAB AS ZPPTN, Z.PPLCAB AS ZPPLC, Z.PGSCAB AS ZPGSC,
                    Z.PSDUAB AS ZPSDU, Z.SSTTAB AS ZSSTT, Z.PCPUAB AS ZPCPU, Z.PPMCAB AS ZPPMC, Z.PCMTAB AS ZPCMT
                FROM WAVEDLIB.FAB00 AS Z
                INNER JOIN (
                    SELECT X.PSHN9D AS XPSHN
                    FROM WAVEDLIB.F9D00 AS X
                    WHERE X.EPFU9D BETWEEN '${config.startDate}' AND '${config.endDate}'
                    AND SUBSTRING(X.LN1C9D,1,2) = '${config.lineCode}'
                ) ON Z.PSHNAB = XPSHN
            )
            INNER JOIN (
                SELECT CPR, MAX(NO) AS MAX_NO
                FROM (
                    SELECT ROW_NUMBER() OVER(ORDER BY C.PSHNAB) AS NO,
                        C.PSHNAB AS CPR, C.PPTNAB AS CPPTN, C.PPLCAB AS CPPLC, C.PGSCAB AS CPGSC
                    FROM WAVEDLIB.FAB00 AS C
                    INNER JOIN (
                        SELECT Y.PSHN9D AS YPSHN
                        FROM WAVEDLIB.F9D00 AS Y
                        WHERE Y.EPFU9D BETWEEN '${config.startDate}' AND '${config.endDate}'
                        AND SUBSTRING(Y.LN1C9D,1,2) = '${config.lineCode}'
                    ) ON C.PSHNAB = YPSHN
                )
                GROUP BY CPR
            ) ON ZNO = MAX_NO
        ) ON A.PSHN9D = ZPR
        LEFT JOIN WAVEDLIB.FBY00 ON PSHNBY = A.PSHN9D
        LEFT JOIN (
            SELECT PSHN9H, PCPU9H, PCMT9H, PCPQ9H
            FROM WAVEDLIB.F9H00
            WHERE SUBSTRING(LN1C9H,1,2) = '41' AND PCPU9H <> 0
        ) ON PSHN9H = A.PSHN9D
    WHERE A.EPFU9D BETWEEN '${config.startDate}' AND '${config.endDate}'
        AND SUBSTRING(A.LN1C9D,1,3) = '${config.lineCode}'
        AND A.PSDU9D > 0
    GROUP BY A.LN1C9D||'-'|| A.LN2C9D, CN1I09, CASE WHEN A.PDSC9D = '1' THEN 'REMAKE' ELSE '' END,
        PSHN9Y, PPDNBY, PSSQBY, A.PSHN9D, A.ITMC9D, IT1IA0, IT2IA0, IT3IA0,
        CASE WHEN IT2IA0 LIKE '%WATER%' THEN 'O' WHEN IT3IA0 LIKE '%WATER%' THEN 'O' ELSE '' END,
        CLSCA0, SFNCA0, A.LNGV9D, A.LUNC9D, A.CLRC9D, A.PSCQ9D, PSDU9G, PSDT9G,
        CH_D, CH_T, CH_QTY, A.EPFU9D, A.EPFT9D, A.PCPU9D, A.PCMT9D,
        CASE WHEN A.PCPU9D <= A.EPFU9D THEN 'ONTIME' ELSE 'DELAY' END,
        CASE WHEN A.PCPU9D || A.PCPC9D <= A.EPFU9D || A.EPFC9D THEN 'ONTIME' ELSE 'DELAY' END,
        CASE WHEN A.PCPU9D > '0' THEN 'COMPLETED' ELSE MC_TYPE || ' ' || MC_LINE || STATUS END,
        CASE WHEN A.PCPU9D > 0 THEN 'COMPLETED' ELSE 'NOT COMPLETE' END,
        A.PCPQ9D, MC_DATE, MC_TIME, STATUS, MC_TYPE, MC_LINE, E.RADUV1, E.RADTV1,
        F.RADUV1, F.RADTV1, TAPE_OUT, SL_OUT, TP_AREA, SL_AREA, PCPU9H, PCMT9H,
        PCPQ9H, A.PSCN9D, TQ090.RUPUQ0, TQ090.RUPTQ0
    FETCH FIRST ${config.rowLimit} ROWS ONLY`
};

module.exports = productionQueries;
